config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  
  devise_scope :user do
    post 'users/guest_sign_in' => 'application#guest_sign_in'
  end

  get 'home/about' => 'homes#about'

  get 'books/search' => 'books#search'

  devise_for :users

  resources :users, :only => [:index, :show, :edit, :update]

  resources :books do
    resources :post_comments, :only => [:create, :destroy]
    resource :favorites, :only => [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body,  presence: true, length: { maximum: 200 }

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :book
  belongs_to :user

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum:2, maximum:20 },uniqueness: true
  validates :introduction, length: { maximum:50 }

  #validates :introduction,  presence: true

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # def self.guest
  #   find_or_create_by!(name: 'guest@example.com') do |user|
  #     user.password = SecureRandom.urlsafe_base64
  #     user.name = 'ゲストユーザー'
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!,except: [:top, :about, :guest_sign_in]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_up_path_for(resource)
    user_path(@user.id)
  end

  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
    sign_in user
    redirect_to user_path(user.id), notice: 'ゲストユーザーとしてログインしました'
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.page(params[:page]).reverse_order
    @book = Book.new
    @user_id = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice:'You have created book successfully.'
    else
      @books = Book.page(params[:page]).reverse_order
      @user_id = current_user
      render :index
    end
  end

  def show
    @book_find = Book.find(params[:id])
    @user = current_user
    @book = Book.new
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user_id = current_user
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice:"You have updated book successfully."
    else
      @user_id = current_user
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def search
    if params[:title].present?
      @books = Book.where('title LIKE ?', "%#{params[:title]}%")
    else
      @books = Book.none
    end
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to book_path(book)
  end

 def destroy
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.find_by(book_id: book.id)
   favorite.destroy
   redirect_to book_path(book)
 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @user_id = current_user
  end

  def about
    @user_id = current_user
  end

  # def guest_sign_in
  #   user = User.find_or_create_by!(email: 'guest@example.com') do |user|
  #     user.password = SecureRandom.urlsafe_base64
  #     user.name = 'ゲストユーザー'
  #   end
  #   sign_in user
  #   redirect_to user_path(user.id), notice: 'ゲストユーザーとしてログインしました'
  # end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(params[:book_id])
  end

  def destroy
    PostComment.find_by(id:params[:id], book_id:params[:book_id]).destroy
    redirect_to book_path(params[:book_id])

  end


  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).reverse_order
    @user_id = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @user_id = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    @user_id = current_user

    if @user != current_user
      redirect_to user_path(current_user), alert: "#{@user.name}の情報は変更できません"
    elsif current_user.email == 'guest@example.com'
      redirect_to user_path(current_user), alert: 'ゲストユーザー情報は変更できません'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      @user_id = current_user
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_left.html.erb
    <!--左側-->
    <dev class="col-md-3">
      <h2>User info</h2>

      <%= attachment_image_tag user_id, :profile_image, size: "50x50", format:'jpeg', fallback:"no_image.jpg" %>

        <table class="table my-3">
          <tr>
            <th>name</th>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= current_user.introduction %></td>
          </tr>
        </table>

      <div class="row-fluid">
        <%= link_to edit_user_path(current_user) do %>
          <span class="btn btn-outline-secondary btn-block fas fa-user-cog"></span>
        <% end %>
      </div>

      <h2 class="my-3">New book</h2>
      <%= form_with model:book, local:true do |f| %>
      <div class="form-group">
      <h6 class="my-2">Title</h6>
      <%= f.text_field :title ,class:"form-control" %>
      </div>
      <div class="form-group">
      <h6 class="my-2">Opinion</h6>
      <%= f.text_area :body ,class:"form-control" %>
      </div>
      <div class="my-2">
      <%= f.submit "Create Book",class:"btn-success text-light rounded " %>
      </div>
      <% end %>
    </dev>
    <!--左側ここまで-->

app/views/books/edit.html.erb
<div class="text-danger mt-3 ml-5">
  <% if @book.errors.any? %>
    <div class="mb-2"><%= @book.errors.count %>errors prohibited this obj from being saved:</div>
    <% @book.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %>
</div>

<div class="container mt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
        <%= form_with model:@book, local: true do |f| %>
        <div class="form-group">
          <h6 class="my-2">Title</h6>
            <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <h6 class="my-2">Opinion</h6>
            <%= f.text_area :body, class:"form-control" %>
        </div>
        <div>
        <%= f.submit "Update Book",class:"btn-success text-light rounded my-2" %>
        </div>
        <% end %>

      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="text-danger mt-3 ml-5">
  <% if @book.errors.any? %>
    <div class="mb-2"><%= @book.errors.count %>errors prohibited this obj from being saved:</div>
    <% @book.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  <% end %>
</div>

<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <!--左側-->
    <%= render 'books/left',book:@book,user_id:@user_id %>
    <!--左側ここまで-->
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "30x30", format:'jpeg', fallback:"no_image.jpg" %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td><%= link_to "コメント#{book.post_comments.count}件", book_path(book.id), class:"small" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
     <%= paginate @books %>
    </div>
    <!--右側ここまで-->
  </div>
</div>

app/views/books/search.html.erb
<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <div class="col-md-8 offset-md-1">
      <h1>Book search</h1>
      <div class="my-3">
      <%= form_with url: books_search_path, method: :get, local: true do |f| %>
        <%= f.text_field :title %>
        <%= f.submit :search, class:"my-2 btn btn-sm btn-primary" %>
      <% end %>
      </div>

      <table class="table">
      <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "30x30", format:'jpeg', fallback:"no_image.jpg" %>
              <% end %>
          </td>
          <td>
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          <td><%= book.body %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <!--左側-->
    <dev class="col-md-3">
      <h2>User info</h2>

       <%= attachment_image_tag @book_find.user, :profile_image, size: "50x50", format:'jpeg', fallback:"no_image.jpg" %>

       <table class="table my-3">
          <tr>
            <th>name</th>
            <td><%= @book_find.user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @book_find.user.introduction %></td>
          </tr>
        </table>

      <div class="row-fluid">
        <%= link_to edit_user_path(@book_find.user) do %>
          <span class="btn btn-outline-secondary btn-block fas fa-user-cog"></span>
        <% end %>
      </div>

      <h2 class="my-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
      <h6 class="my-2">Title</h6>
      <%= f.text_field :title ,class:"form-control" %>
      </div>
      <div class="form-group">
      <h6 class="my-2">Opinion</h6>
      <%= f.text_area :body ,class:"form-control" %>
      </div>
      <div class="my-2">
      <%= f.submit "Create Book",class:"btn-success text-light rounded " %>
      </div>
      <% end %>
    </dev>
    <!--左側ここまで-->
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
       <tr>
          <td>
            <%= attachment_image_tag @book_find.user, :profile_image, size: "30x30", format:'jpeg', fallback:"no_image.jpg" %><br>
            <%= link_to user_path(@book_find.user) do %>
              <%= @book_find.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@book_find) do %>
              <%= @book_find.title %>
            <% end %>
          </td>
          <td>
            <%= @book_find.body %>
          </td>
          <% if @book_find.user == current_user %>
          <td><%= link_to "Edit",edit_book_path(@book_find.id), class:"btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy",book_path(@book_find), class:"btn btn-sm btn-danger",method: :delete, data: { confirm: '削除しますか？' } %></td>
          <% end %>
        </tr>
      </table>

      <% if @book_find.favorited_by?(current_user) %>
        <p>
          <%= link_to book_favorites_path(@book_find), method: :delete, class:"mb-3" do %>
            ♥<%= @book_find.favorites.count %> いいね
          <% end %>
        </p>
      <% else %>
        <p>
          <%= link_to book_favorites_path(@book_find), method: :post do %>
            ♡<%= @book_find.favorites.count %> いいね
          <% end %>
        </p>
      <% end %>

      <div class="my-3">
        <div class="border-bottom"><%= @book_find.post_comments.count %>件のコメント</div>
        <div><%= attachment_image_tag @post_comment.user, :profile_image, size: "30x30", format:'jpeg' %></div>
        <% @book_find.post_comments.each do |post_comment| %>
          <div class="border-bottom">
            <div><%= post_comment.comment %></div>
            <div><%= post_comment.user.name %></div>
            <div class="mb-1 small"><%= post_comment.created_at.strftime('%Y/%m/%d') %></div>
            <% if post_comment.user == current_user %>
             <%= link_to "削除", book_post_comment_path(post_comment.book,post_comment), method: :delete, class:"small" %>
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="new_comment">
        <%= form_with(model:[@book_find,@post_comment], local:true) do |f| %>
          <%= f.text_area :comment,rows:'5' %>
          <div><%= f.submit "Create Comment", class:"btn btn-sm btn-success" %></div>
        <% end %>
      </div>

    </div>
    <!--右側ここまで-->
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="pt-3 mx-auto">
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 pt-3">
      <h1>welcome to <strong><i class="fas fa-book"></i>Bookers</strong>!!</h1>
      <p>In <strong><i class="fas fa-book"></i>Bookers</strong>,</p>
      <p>you can share and exchange your opinions,inpressions,and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <% if user_signed_in? %>
          <div class="row">
            <%= link_to "Log in",user_path(current_user), class:"btn btn-primary btn-sm btn-block" %>
          </div>
          <div class="row">
            <%= link_to "Sign up",user_path(current_user), class:"btn btn-success btn-sm btn-block my-3" %>
          </div>
          <div class="row">
            <%= link_to "Guest log in",user_path(current_user), class:"btn btn-info btn-sm btn-block" %>
          </div>
        <% else %>
          <div class="row">
            <%= link_to "Log in",new_user_session_path, class:"btn btn-primary btn-sm btn-block" %>
          </div>
          <div class="row">
            <%= link_to "Sign up",new_user_registration_path, class:"btn btn-success btn-sm btn-block my-3" %>
          </div>
          <div class="row">
            <%= link_to "Guest log in",users_guest_sign_in_path, method: :post, class:"btn btn-info btn-sm btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <!--ヘッダー-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">Bookers</a>
          <button class="navbar-toggler bg-dark rounded ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
            <%= link_to " Home ",user_path(current_user),class:'fas fa-home nav-link text-light' %>
            </li>
            <li>
            <%= link_to " Users ",users_path,class:'fas fa-users nav-link text-light' %>
            </li>
            <li>
            <%= link_to " Books ",books_path,class:'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
            <%= link_to " Search ",books_search_path,class:'fas fa-search nav-link text-light' %>
            </li>
            <li>
            <%= link_to " logout ",destroy_user_session_path, method: :delete,class:'fas fa-sign-out-alt nav-link text-light' %>
            </li>
          <% else %>
            <li>
            <%= link_to " Home ",root_path,class:'fas fa-home nav-link text-light' %>
            </li>
            <li>
            <%= link_to " About ",home_about_path,class:'fas fa-link nav-link text-light' %>
            </li>
            <li>
            <%= link_to " sign up ",new_user_registration_path,class:'fas fa-user-plus nav-link text-light' %>
            </li>
            <li>
           <%= link_to " login ",new_user_session_path,class:'fas fa-sign-in-alt nav-link text-light' %>
            </li>
          <% end %>
          </ul>
         </div>
        </div>
      </nav>
    </header>
    <!--ここまで-->
    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <% if message_type == "alert" %>
          <%= content_tag :div, message, class: :"alert alert-danger" %>
        <% else %>
          <%= content_tag :div, message, class: :"alert alert-success" %>
        <% end %>
      <% end %>
      <%= yield %>
    </main>
    <!--フッター-->
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    <!--ここまで-->
  </body>
</html>

app/views/users/edit.html.erb
<div class="text-danger mt-3 ml-5">
<% if @user.errors.any? %>
  <div class="mb-2"><%= @user.errors.count %>errors prohibited this obj from being saved:</div>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %><br>
  <% end %>
<% end %>
</div>

<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user ,local:true do |f| %>
      <div class="form-group">
      <h6>Name</h6>
      <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
      <h6>Image</h6>
      <%= attachment_image_tag @user,:profile_image,size:"50x50" %>
      <%= f.attachment_field :profile_image,placeholder:"ファイルを選択" %>
      </div>
      <div class="form-group">
      <h6>Introduction</h6>
      <%= f.text_area :introduction, class:"form-control" %>
      </div>
      <div class="my-2">
      <%= f.submit "Update User",class: "btn btn-sm btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <%= render "books/left", book:@book, user_id:@user_id %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>

      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size: "30x30", format:'jpeg', fallback:"no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show",user_path(user.id) %></td>
        </tr>
        <% end %>
      </table>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0 pt-3">
  <div class="row">
    <!--左側-->
    <dev class="col-md-3">
      <h2>User info</h2>

       <%= attachment_image_tag @user, :profile_image, size: "50x50", format:'jpeg', fallback:"no_image.jpg" %>

      <% if @book.user == current_user %>
        <table class="table my-3">
          <tr>
            <th>name</th>
            <td><%= current_user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= current_user.introduction %></td>
          </tr>
          
        </table>
      <% else %>
        <table class="table my-3">
          <tr>
            <th>name</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>introduction</th>
            <td><%= @user.introduction %></td>
          </tr>
        </table>
      <% end %>

      <div class="row-fluid">
        <%= link_to edit_user_path(@user) do %>
          <span class="btn btn-outline-secondary btn-block fas fa-user-cog"></span>
        <% end %>
      </div>

      <h2 class="my-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
      <h6 class="my-2">Title</h6>
      <%= f.text_field :title ,class:"form-control" %>
      </div>
      <div class="form-group">
      <h6 class="my-2">Opinion</h6>
      <%= f.text_area :body ,class:"form-control" %>
      </div>
      <div class="my-2">
      <%= f.submit "Create Book",class:"btn-success text-light rounded " %>
      </div>
      <% end %>
    </dev>
    <!--左側ここまで-->
    <!--右側-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>

      <table class="table">
        <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, size: "30x30", format:'jpeg', fallback:"no_image.jpg" %>
            <% end %>
          </td>
          <td>
            <%=link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!--右側ここまで-->
  </div>
</div>